default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>

development:
  <<: *default
  database: design_history_development

test:
  <<: *default
  database: design_history_test

production:
  <<: *default
  database: design_history_production
